comment:
  on-update: recreate
  header: |
    This is the header

  footer: |
    ---
    Automated comment created by [PR Commenter](https://github.com/exercism/pr-commenter-action) :robot:.

  snippets:
    - id: snippet
      files:
        - '**/*'
      body: |
        https://{{app_name}}.{{domain}} created {{now}}