name: Ephemeral
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR key
        id: key
        run: KEY="$GITHUB_REPOSITORY-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"; \
          SHA=`echo -n "$KEY" | openssl dgst -binary -sha256 | xxd -p`; \
          echo ::set-output name=raw::"$KEY" \
          echo ::set-output name=full_sha::"$SHA" \
          echo ::set-output name=sha::"${SHA:0:8}"
      - run: echo "${{ steps.key.outputs.raw }}"
      - run: echo "${{ steps.key.outputs.full_sha }}"
      - run: echo "${{ steps.key.outputs.sha }}"